---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - nginx
    - nginx-full
    - nginx-common

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/{{ item }}"
  with_items:
    - nginx.conf
    - conf.d/custom_vhost.conf
    - conf.d/php-fpm.conf
  notify:
    - restart nginx

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - nginx
