---

- name: install key
  apt_key:
    url: "{{ nginx_apt_key_url }}"
    state: present
  register: nginx_key_installed

- name: add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  when: nginx_key_installed|success
  register: nginx_repo_installed
  with_items: "{{ nginx_apt_repositories }}"

- name: update apt cache
  apt:
    update_cache: yes
  when: nginx_repo_installed|changed

- name: install apt packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  when: nginx_repo_installed|success
  with_items: "{{ nginx_packages }}"

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "{{ nginx_config_path }}/{{ item }}"
  with_items:
    - nginx.conf
    - conf.d/custom_vhost.conf
    - conf.d/php-fpm.conf
  notify:
    - restart nginx
  tags: nginx_config

- name: check nginx default root
  file:
    path: "{{ nginx_default_root }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user_group }}"
    mode: 0755
  tags: nginx_config

- name: add default index
  template:
    src: index.html.j2
    dest: "{{ nginx_default_root}}/index.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user_group }}"
    mode: 0755
  when: nginx_default_vhost_enabled
  tags: nginx_config

- name: service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nginx
